export const noButtonTexts = [
    "No",
    "Are you sure?",
    "Reconsider this",
    "Have a heart, come on",
    "Think again, please",
    "Are we not meant to be?",
    "Give it another thought",
    "Surely, you jest?",
    "Can't we be together?",
    "Is it really a no?",
    "Last chance, yes?",
    "Heartbreaker!",
    "Final answer?",
    "Don't be so quick to decide",
    "You might regret this!",
    "Wait, think it over",
    "But we're perfect together!",
    "Isn't love worth a chance?",
    "Who else will bring you flowers?",
    "Say yes, make my day",
    "Could you reconsider, for me?",
    "Your heart says yes, doesn't it?",
    "Imagine us, together",
    "Why not take a leap of faith?",
    "A yes could change everything",
    "Think of the possibilities!",
    "Isn't life too short for no's?"
  ];